---
- name: Creation client nfs
  hosts: nfs-client
  become: true
  vars:
    nfs_server: "192.168.182.129"
    os_family: "{{ ansible_os_family }}"
    nfs_chemin: "/srv/nfs"
  tasks:
    - name: Installation des paquets RedHat
      ansible.builtin.packege:
        name: "{{ 'nfs-utils' if os_family == 'Redhad' else 'nfs-comon' }}"
        state: present

    - name: Mount du fs nfs
      ansible.posix.mount:
        scr: "{{ nfs_server }}:{{ nfs_chemin }}"
        fstype: nfs
        state: mounted
      
